export declare const getAllListings: (filters: {
    category?: string | undefined;
    search?: string | undefined;
    state?: string | undefined;
}) => Promise<{
    id: string;
    title: string;
    category: string;
    purpose: string;
    location: string;
    state: string;
    district: string;
    area: number;
    areaUnit: string;
    price: number;
    currency: string;
    verified: boolean;
    authority: string;
    tags: string[];
    imageUrl: string;
    description: string;
    sellerName: string;
    sellerEmail: string;
    sellerPhone: string;
    createdAt: Date;
    updatedAt: Date;
    sellerId: string;
}[] | {
    id: string;
    title: string;
    description: string;
    category: import(".prisma/client").$Enums.ListingCategory;
    purpose: import(".prisma/client").$Enums.ListingPurpose;
    location: string;
    latitude: number | null;
    longitude: number | null;
    area: number;
    areaUnit: string;
    zoning: string | null;
    usageType: string | null;
    authority: string | null;
    verifiedBadge: boolean;
    verificationSource: string | null;
    sellerId: string;
    createdAt: Date;
    updatedAt: Date;
}[]>;
export declare const getListingById: (id: string) => Promise<{
    id: string;
    title: string;
    description: string;
    category: import(".prisma/client").$Enums.ListingCategory;
    purpose: import(".prisma/client").$Enums.ListingPurpose;
    location: string;
    latitude: number | null;
    longitude: number | null;
    area: number;
    areaUnit: string;
    zoning: string | null;
    usageType: string | null;
    authority: string | null;
    verifiedBadge: boolean;
    verificationSource: string | null;
    sellerId: string;
    createdAt: Date;
    updatedAt: Date;
} | {
    id: string;
    title: string;
    category: string;
    purpose: string;
    location: string;
    state: string;
    district: string;
    area: number;
    areaUnit: string;
    price: number;
    currency: string;
    verified: boolean;
    authority: string;
    tags: string[];
    imageUrl: string;
    description: string;
    sellerName: string;
    sellerEmail: string;
    sellerPhone: string;
    createdAt: Date;
    updatedAt: Date;
    sellerId: string;
} | null>;
export declare const createListing: (listingData: any) => Promise<{
    id: string;
    title: string;
    description: string;
    category: import(".prisma/client").$Enums.ListingCategory;
    purpose: import(".prisma/client").$Enums.ListingPurpose;
    location: string;
    latitude: number | null;
    longitude: number | null;
    area: number;
    areaUnit: string;
    zoning: string | null;
    usageType: string | null;
    authority: string | null;
    verifiedBadge: boolean;
    verificationSource: string | null;
    sellerId: string;
    createdAt: Date;
    updatedAt: Date;
}>;
//# sourceMappingURL=listings.service.d.ts.map